# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Recupery2' do

pod 'CircleMenu', '~> 0.0.5'
pod 'LayerKit'

end

target 'Recupery2Tests' do

end

target 'Recupery2UITests' do

end
